#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/init.sh

for sample in $SAMPLES
do
	echo "sample: $sample"
	$DIR/remote_dispatch $sample
	echo "-----------------------------------------------"
done
