#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/init.sh

usage() {
cat << EOF
usage: $0 <sample name> <local path>
EOF
	exit 1
}

if [ $# -ne 2 ]
then
	usage
fi

sample=$1
fastq_path=$2
fastq_file=`basename $2`

echo "processing sample $sample from path $fastq_path with fastq filename $fastq_file"

# first, make sure the local files exist
is_file_readable $fastq_path
# second, assemble what the remote path will be
remote_fastq_path=data/$sample/Raw_Data/$fastq_file
echo --
echo $remote_fastq_path/$fastq_file
echo --

# now, let's check if the local copy of the remote path exists, if so, don't recopy
# the local copy
mkdir -p `dirname "$remote_fastq_path"`
if [ ! -e "$remote_fastq_path" ]
then
	gnucp "$fastq_path" $remote_fastq_path
else
	echo "skipping copying of fastq into data directory"
fi

# don't upload if it already exists
remote_fastq_exists=`remote_file_exists $remote_fastq_path`
if [ -n "$remote_fastq_exists" ]
then
	echo "skipping upload of fastq $remote_fastq_path"
else
	echo "sending fastq $remote_fastq_path"
	send_path_to_remote $remote_fastq_path
fi
